# Generated by Django 4.0.6 on 2022-08-02 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0008_addresses_alter_book_author_author_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresses',
            new_name='Address',
        ),
    ]
