# Generated by Django 4.0.6 on 2022-08-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0010_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
